scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/known_SNPs/known_SNPs_analysis_G_revised/additive_model/result/additive_model_G_new.xlsx /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/known_SNPs/known_SNPs_analysis_G_revised/additive_model/result/.

scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/known_SNPs/known_SNPs_analysis_G_revised/intrinsic_subtypes_pc_additive/result/intrinsic_subtypes_model_G.xlsx /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/known_SNPs/known_SNPs_analysis_G_revised/intrinsic_subtypes_pc_additive/result/.


scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/known_SNPs/known_SNPs_analysis_G_revised/ERPosvesNeg/result/binary_model.xlsx /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/known_SNPs/known_SNPs_analysis_G_revised/ERPosvesNeg/result/.
