scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/plot/man.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/plot/man_filter.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/plot/man_filter_Montse.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/plot/qq.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/plot/qq_filter.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_fixed_baseline/result/

scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/plot/man.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/plot/man_filter.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/plot/man_filter_Montse.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/plot/qq.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/plot/qq_filter.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/
scp zhangh24@biowulf.nih.gov:/spin1/users/zhangh24/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/plot/qq_filter_Ju.png /Users/zhangh24/GoogleDrive/breast_cancer_data_analysis/whole_genome_age/ICOG/ERPRHER2GRADE_casecase/result/